# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_auto_20220812_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(max_length=255, upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
